//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dashboardQ40.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dashboardQ40.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Q.40.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteplant 2025 - Quality Dashboard 4.0.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Zones.
        /// </summary>
        public static string OperationalZones {
            get {
                return ResourceManager.GetString("OperationalZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant 1.
        /// </summary>
        public static string Plant1 {
            get {
                return ResourceManager.GetString("Plant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant 2.
        /// </summary>
        public static string Plant2 {
            get {
                return ResourceManager.GetString("Plant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant 3.
        /// </summary>
        public static string Plant3 {
            get {
                return ResourceManager.GetString("Plant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        public static string RegionNoreste {
            get {
                return ResourceManager.GetString("RegionNoreste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string RegionNorte {
            get {
                return ResourceManager.GetString("RegionNorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string RegionOccidente {
            get {
                return ResourceManager.GetString("RegionOccidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific.
        /// </summary>
        public static string RegionPacifico {
            get {
                return ResourceManager.GetString("RegionPacifico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Traceability Report.
        /// </summary>
        public static string TraceabilityReport {
            get {
                return ResourceManager.GetString("TraceabilityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome:.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
